# Ingress ALB público para a API de recomendação.
# HTTPS com certificado ACM wildcard (*.pocsarcotech.com).
# HTTP redireciona automaticamente para HTTPS.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recsys-api
  namespace: models
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health/status
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:177300752486:certificate/eebc6271-527b-45a6-99b8-b7b888cdbdc2
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: techchallenger2.pocsarcotech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recsys-api
                port:
                  number: 80
